version: "3.8"

services:
  mongodb:
    image: mongo:latest
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
  app:
    depends_on:
      - mongodb
    build: .
    ports:
      - ${PORT}:${PORT}
    env_file: .env
volumes:
  mongodb:
  mongoconfig:
